import SvgIcon from '@/components/SvgIcon.vue';
import type { App, Plugin } from 'vue';
// Register the SVG sprite generated by vite-plugin-svg-icons.
import 'virtual:svg-icons-register';

const svgIconsPlugin: Plugin = {
  install(app: App): void {
    app.component('svg-icon', SvgIcon);
  },
};

export default svgIconsPlugin;
